# ----
# Site

title: DOC by SALIM.LINK
description: General Documentation For My Projects.
url: https://doc.salim.link
google_analytics_key:
permalink: pretty
baseurl: https://doc.salim.link

# -----
# Build

timezone: Europe/Paris

collections:
  jekyll:
    title: Jekyll
    position_number: 1
  laravel:
    title: Laravel
    position_number: 2
  slimframework:
    title: SlimFramework
    position_number: 3
  reactjs:
    title: ReactJS
    position_number: 4
  nodejs:
    title: NodeJS
    position_number: 5
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENSE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      type: "jekyll"
    values:
      _hide_content: true
  -
    scope:
      type: "laravel"
    values:
      _hide_content: true
  -
    scope:
      type: "slimframework"
    values:
      _hide_content: true
  -
    scope:
      type: "reactjs"
    values:
      _hide_content: true
  -
    scope:
      type: "nodejs"
    values:
      _hide_content: true

# -----------
# CloudCannon

types:
  - get
  - put
  - delete
  - post

languages:
  bash: Bash
  c: C
  css: CSS
  html: HTML
  java: Java
  javascript: JavaScript
  json: JSON
  php: PHP
  python: Python
  ruby: Ruby

_options:
  content_markdown:
    format: p h4 h5 h6
    bold: true
    italic: true
    link: true
    bulletedlist: true
    numberedlist: true
    image: true
    table: true
    styles: /css/editor.css
